name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    # Použijeme tuhle "bublinu" (kontejner), kde všechno funguje na 100%
    container:
      image: ghcr.io/kivy/buildozer:master

    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        run: |
          # V tomto prostředí už je vše nastaveno správně
          buildozer -v android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: IPTV-Master-APK-Final
          path: bin/*.apk
