name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    # Ubuntu 22.04 je pro Kivy nejstabilnější, verze 24 je moc nová
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libtool pkg-config autoconf automake libffi-dev zlib1g-dev libssl-dev gettext

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade buildozer Cython==0.29.33

      - name: Build APK
        run: |
          # Vynecháme 'yes |' a použijeme parametr, který vše odsouhlasí uvnitř Buildozeru
          buildozer -v android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"
          BUILD_ANDROID: "1"
