name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # Nastavení Javy 11 (nutné pro stabilitu Gradle)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Instalace potřebných systémových knihoven
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libtool pkg-config autoconf automake libffi-dev zlib1g-dev libssl-dev gettext

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Instalace Buildozeru a Cythonu
      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade buildozer Cython==0.29.33

      # Samotný Build s pročištěním starých chyb
      - name: Build APK
        run: |
          # Odstranění cest k NDK, které vnucuje GitHub
          unset ANDROID_NDK_HOME
          unset ANDROID_NDK_ROOT
          
          # Kompletní vyčištění předchozích pokusů
          buildozer android clean
          
          # Spuštění buildu
          buildozer -v android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      # Nahrání hotového APK souboru jako Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: IPTV-Master-v30-APK
          path: bin/*.apk
